### ISSUE TITLE
关于geograph的代码问题

### ISSUE THREAD

**Issue by ShelveyJ** [Fang6ang/KBGNN#1]
感谢作者开源论文相关代码，想请问一下源代码GeoGraph中如下四行代码的实现是否有问题：
![image](https://user-images.githubusercontent.com/52660191/215465519-d8f50df3-6543-4643-9ce0-eb34dc88e8c2.png)
据我所知，使用to_undireted之后，edge_index和concatenate之后的dist_vec并不是一一匹配的。

**Comment by Yifang-Qin** [comment]
您好，您提到的代码确实会带来一定的风险。to_undirected 内部调用 coalesce 函数会对 edge_index 进行按行的重排，因此代码有效的前提是需要保证 dist_edges 输入就是按行排序的，在 process_data.py 数据预处理的过程中保证了这一点。
不过这依然是借助了 torch_geometric 库没有保证的特性所实现的功能，因此我们更新了这部分的代码来提高可靠性。非常感谢您指出的问题。
